import Link from "next/link";
import Image from "next/image";

export default function AboutPage() { return <main>
  <section className="page-hero about-hero"><video autoPlay muted loop playsInline preload="metadata"><source src="/arix-field-loop.mp4" type="video/mp4" /></video><div className="hero-shade" /><div className="shell"><p className="eyebrow">About ARIX</p><h1>Intelligence designed<br />for the <span>real field.</span></h1><p>We are building a more precise relationship between crop protection, field data, and autonomous systems.</p></div></section>
  <section className="statement section shell"><p className="section-index">01 / Why ARIX</p><div className="statement-copy"><h2>Better decisions begin<br /><span>with better visibility.</span></h2><p>Crop disease is spatial, but traditional treatment is often uniform. ARIX exists to close that gap — giving growers a clearer picture of where disease pressure is developing and creating a foundation for more targeted intervention.</p></div></section>
  <section className="section shell origin-grid"><div className="origin-card wheat"><Image src="/arix-drone-concept.png" alt="ARIX concept drone surveying a wheat field" fill sizes="(max-width: 760px) 100vw, 50vw" /><div className="origin-card-shade" /><span>Starting crop</span><strong>Wheat</strong><p>Selected for local field access, regional relevance, and well-studied disease classes.</p></div><div className="origin-card location"><span>Built from</span><strong>Pakistan</strong><p>Grounded in local agricultural realities, with ambitions to scale crop intelligence globally.</p></div><div className="origin-card approach"><span>Our approach</span><strong>Prove. Learn. Automate.</strong><p>Validate the intelligence pipeline before adding autonomous complexity.</p></div></section>
  <section className="section shell team-placeholder"><p className="section-index">02 / The team</p><div><h2>A cross-functional build.</h2><p>ARIX brings together business operations, hardware and flight control, AI, mapping, and software — with agronomist guidance built into the validation loop.</p><div className="team-streams"><span>Business & Operations</span><span>Hardware & Flight</span><span>AI, Mapping & Software</span><span>Agronomy Advisory</span></div></div></section>
  <section className="cta-section shell"><div><p className="eyebrow">Partner with ARIX</p><h2>Bring the next field trial closer.</h2></div><Link className="button button-primary" href="/contact">Contact the team <span>↗</span></Link></section>
  </main>; }
