import Link from "next/link";
import { ArbotsReveal } from "../../components/ArbotsReveal";

export default function ArbotsTeamPage() {
  return <main className="arbots-main arbots-team-page">
    <section className="arbots-team-hero"><div className="arbots-grid" aria-hidden="true" /><div className="arbots-team-x arbots-team-v" aria-hidden="true">V</div><div className="arbots-shell"><p className="arbots-kicker">ARIX / VBOT</p><h1>The team behind<br /><span>VBot.</span></h1><p>One cross-functional team shaping the intelligence, hardware, character, and emotional presence of VBot.</p></div></section>
    <section className="arbots-section arbots-parent"><div className="arbots-shell arbots-parent-grid"><ArbotsReveal><p className="arbots-index">01 / Built under ARIX</p><h2>A robotics initiative<br />with a <span>human focus.</span></h2></ArbotsReveal><ArbotsReveal delay={.1}><p>ARIX is the parent brand behind VBot. While ARIX explores physical AI across real-world systems, VBot focuses that ambition on emotionally engaging companion robotics.</p><p>VBot is the first concentrated expression of that initiative: one robot, one identity, and a product experience designed as a whole.</p><Link className="arbots-text-link bright" href="/">Visit ARIX →</Link></ArbotsReveal></div></section>
    <section className="arbots-section arbots-team"><div className="arbots-shell"><ArbotsReveal className="arbots-section-head"><p className="arbots-index">02 / The team</p><h2>Team<br /><span>ARIX.</span></h2></ArbotsReveal><ArbotsReveal className="arbots-about-grid" delay={.08}><div className="arbots-about-lead">VBot is created by one cross-functional group: Team ARIX.</div><div><p>The team works across product, hardware, software, embedded systems, artificial intelligence, design, and robotics as one unit.</p><p>Individual roles and member profiles are intentionally not listed at this stage.</p></div></ArbotsReveal></div></section>
    <section className="arbots-team-mission"><div className="arbots-shell"><ArbotsReveal><p className="arbots-index">03 / Our mission</p><blockquote>“Make robotics more personal, accessible, and emotionally meaningful—without losing the discipline of building something real.”</blockquote></ArbotsReveal></div></section>
    <section className="arbots-waitlist"><div className="arbots-shell arbots-back-product"><div><p className="arbots-kicker">Meet what we are building.</p><h2>One team.<br /><span>One VBot.</span></h2></div><Link className="arbots-button primary" href="/arbots">Back to the product <span>→</span></Link></div></section>
  </main>;
}
